### ISSUE TITLE
Android robots can ignore the domain plug-in lands permission

### ISSUE THREAD

**Issue by zhenjing666** [baked-libs/dough#196]
## Description (Required)

The robot can be placed at the edge of the lands territory for square digging and other operations
## Steps to reproduce the Issue (Required)

1. Place the robot on the edge of lands

2. Execute the command of digging forward

3. Dig out the blocks in the territory
## Expected behavior (Required)

broken the block
## Server Log / Error Report

```
[14:47:31 ERROR]: [dough: protection] An Error occured while querying the Protection Module: "Lands v6.26.0"
java.lang.NoSuchFieldError: BLOCK_BREAK
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.modules.LandsProtectionModule.convert(LandsProtectionModule.java:56) ~[Slimefun4 - DEV 1035 (git 0b7c6).jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.modules.LandsProtectionModule.hasPermission(LandsProtectionModule.java:48) ~[Slimefun4 - DEV 1035 (git 0b7c6).jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.hasPermission(ProtectionManager.java:174) ~[Slimefun4 - DEV 1035 (git 0b7c6).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.items.androids.MinerAndroid.dig(MinerAndroid.java:81) ~[Slimefun4 - DEV 1035 (git 0b7c6).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.items.androids.Instruction.lambda$static$6(Instruction.java:105) ~[Slimefun4 - DEV 1035 (git 0b7c6).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.items.androids.Instruction.execute(Instruction.java:286) ~[Slimefun4 - DEV 1035 (git 0b7c6).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.items.androids.ProgrammableAndroid.executeInstruction(ProgrammableAndroid.java:739) ~[Slimefun4 - DEV 1035 (git 0b7c6).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.items.androids.ProgrammableAndroid.tick(ProgrammableAndroid.java:709) ~[Slimefun4 - DEV 1035 (git 0b7c6).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.items.androids.ProgrammableAndroid$4.tick(ProgrammableAndroid.java:227) ~[Slimefun4 - DEV 1035 (git 0b7c6).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:189) ~[Slimefun4 - DEV 1035 (git 0b7c6).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.lambda$tickLocation$2(TickerTask.java:170) ~[Slimefun4 - DEV 1035 (git 0b7c6).jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-353]        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-353]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-353]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-353]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-353]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-353]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-353]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
## Server specs (Required)

 - Server Software: Paper
 - Minecraft Version: 1.19.3

## FULL plugins list (Required)

lands 6.26.0

**Comment by Angeschossen** [comment]
This can be closed, as it's solved in the latest Lands version
